### ISSUE TITLE
添加apple m1的arm64发行版本

### ISSUE THREAD

**Issue by tenngoxars** [caitouyun/docs#1]
![image](https://user-images.githubusercontent.com/22515339/112026176-e2a51600-8b70-11eb-8689-b19aea9cc80d.png)

**Comment by wangzuo** [comment]
麻烦重新试一下

**Comment by tenngoxars** [comment]
> 麻烦重新试一下

关闭代理之后还是同样的情况

**Comment by wangzuo** [comment]
https://cli.caitouyun.com 这里的能直接下载么?

**Comment by tenngoxars** [comment]
> https://cli.caitouyun.com 这里的能直接下载么?

明白了～您这个网址没有提供 M1 芯片的 darwin arm64 版本，怪不得 404 了～

**Comment by wangzuo** [comment]
奥，我看到了是 `arm64`，我们很快就会加一个版本

**Comment by tenngoxars** [comment]
> 奥，我看到了是 `arm64`，我们很快就会加一个版本

好的，谢谢～

**Comment by wangzuo** [comment]
@tenngoxars 已上传 arm64
